M48
; DRILL file {KiCad (6.0.1)} date Fri Aug  4 16:14:00 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-04T16:14:00-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X2.0709Y-1.6929
X2.0709Y-5.7874
X3.8583Y-1.6929
X3.8583Y-5.7874
T0
M30
